version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: npm install
      - run: npm test || echo "No tests yet"

  android-build:
    docker:
      - image: cimg/android:2023.09
    working_directory: ~/project/android
    steps:
      - checkout
      - run: cd .. && npm install
      - run: ./gradlew assembleDebug

  ios-build:
    macos:
      xcode: "14.3.1"
    steps:
      - checkout
      - run: npm install
      - run: cd ios && pod install
      - run:
          name: Build iOS app
          command: |
            cd ios
            xcodebuild -workspace MyExpoBareApp.xcworkspace \
              -scheme MyExpoBareApp \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android-build:
          requires:
            - build
      - ios-build:
          requires:
            - build
