version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: npm test || echo "No tests yet"

  android-build:
    docker:
      - image: cimg/android:2023.09-node
    # If you’re on free CircleCI, remove this line
    resource_class: large
    working_directory: ~/project
    environment:
      GRADLE_OPTS: "-Xmx1500m -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false"
    steps:
      - checkout
      - run:
          name: Install Ninja
          command: sudo apt-get update && sudo apt-get install -y ninja-build
      - run:
          name: Disable AAPT2 Daemon
          command: echo "android.enableAapt2Daemon=false" >> android/gradle.properties
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "android/build.gradle" }}
      - run:
          name: Build Android app
          command: cd android && ./gradlew assembleDebug --console=plain --info --no-daemon --max-workers=1
          no_output_timeout: 60m
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "android/build.gradle" }}
      - store_artifacts:
          path: android/app/build/outputs/apk/debug
          destination: android-apk

  ios-build:
    macos:
      xcode: "14.3.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - pods-{{ checksum "ios/Podfile.lock" }}
      - run: cd ios && pod install
      - save_cache:
          paths:
            - ios/Pods
          key: pods-{{ checksum "ios/Podfile.lock" }}
      - run:
          name: Build iOS app
          command: |
            cd ios
            xcodebuild -workspace MyExpoBareApp.xcworkspace \
              -scheme MyExpoBareApp \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'
      - store_artifacts:
          path: ios/build
          destination: ios-build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android-build:
          requires:
            - build
      - ios-build:
          requires:
            - build
