version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: npm test || echo "No tests yet"

  android-build:
    docker:
      - image: cimg/android:2023.09-node # Android + Node included
    working_directory: ~/project
    steps:
      - checkout
      - run:
        name: Install Ninja
        command: sudo apt-get update && sudo apt-get install -y ninja-build
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "android/build.gradle" }}
      - run: cd android && ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "android/build.gradle" }}


  
      xcode: "14.3.1"
    


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android-build:
          requires:
            - build
      - ios-build:
          requires:
            - build
