version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: npm test || echo "No tests yet"

  android-build:
    docker:
      - image: cimg/android:2023.09-node
    working_directory: ~/project/android
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "../package-lock.json" }}
      - run: cd .. && npm install
      - save_cache:
          paths:
            - ../node_modules
          key: node-modules-{{ checksum "../package-lock.json" }}
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}

  ios-build:
    macos:
      xcode: "14.3.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - pods-{{ checksum "ios/Podfile.lock" }}
      - run: cd ios && pod install
      - save_cache:
          paths:
            - ios/Pods
          key: pods-{{ checksum "ios/Podfile.lock" }}
      - run:
          name: Build iOS app
          command: |
            cd ios
            xcodebuild -workspace MyExpoBareApp.xcworkspace \
              -scheme MyExpoBareApp \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android-build:
          requires:
            - build
      - ios-build:
          requires:
            - build
